# Generated by Django 4.0.3 on 2022-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_streamer',
            field=models.BooleanField(default=False),
        ),
    ]
