# Generated by Django 4.0.3 on 2022-10-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_group'),
        ('account', '0004_user_group'),
    ]

    operations = [
    ]
