version: '3.9'
services:
  user:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS=
      - DJANGO_SECRET_KEY=
      - DJANGO_ALLOWED_HOSTS=
      - DJANGO_CORS_ORIGIN_WHITELIST=
      - EMAIL_USER=
      - EMAIL_PASS=
      - EMAIL_FROM=
      - JWT_ISSUER=
      - DB_ENGINE=
      - DB_NAME=
      - DB_USER= # The PostgreSQL user (useful to connect to the database)
      - DB_PASSWORD= # The PostgreSQL password (useful to connect to the database)
      - DB_HOST=
      - DB_PORT=
      - JWT_SECRET_KEY=|- -----BEGIN RSA PRIVATE KEY-----  -----END RSA PRIVATE KEY-----
      - JWT_VERIFYING_KEY=|- -----BEGIN PUBLIC KEY----- -----END PUBLIC KEY-----
      - DJANGO_SUPERUSER_EMAIL=
      - DJANGO_SUPERUSER_USERNAME=
      - DJANGO_SUPERUSER_PASSWORD=
      - DJANGO_SUPERUSER_NAME=
    command: sh -c " python manage.py runserver 0.0.0.0:9000"
    #command: gunicorn djangoauthapi1.wsgi:application --log-level=debug --bind 0.0.0.0:9000
    ports:
      - "9000:9000"
    depends_on:
      - auth_db

  auth_db:
    restart: always
    image: postgres:latest
    
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER= # The PostgreSQL user (useful to connect to the database)
    - POSTGRES_PASSWORD= # The PostgreSQL password (useful to connect to the database)
    - POSTGRES_DB= # The PostgreSQL default database 
      
    volumes:
      - ./data/db:/var/lib/postgresql/data
